name: Release and Publish Chrome Extension

on:
  push:
    branches:
      - main

env:
  DIRECTORY: app
  PROJECT_NAME: chrome-emacs
  ZIP_NAME: release.zip

jobs:
  Version:
    runs-on: ubuntu-latest
    outputs:
      created: ${{ steps.daily-version.outputs.created }}
      version: ${{ steps.daily-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Create tag if necessary
        id: daily-version
        uses: fregante/daily-version-action@v2
        with:
          prefix: v
      - name: Ready for publish
        if: steps.daily-version.outputs.created
        run: echo "Version ${{ steps.daily-version.outputs.version }} created"

  BuildAndZip:
    needs: Version
    if: needs.Version.outputs.created
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - run: npm ci
      - name: Build
        run: npm run build
      - name: Zip the app directory for release
        run: |
          cd $DIRECTORY
          zip -r ../${{ env.ZIP_NAME }} ./*
          cd ..
      - name: Upload Zip for Submit Job
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ZIP_NAME }}
          path: ${{ env.ZIP_NAME }}

  Submit:
    needs: BuildAndZip
    if: needs.Version.outputs.created
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.ZIP_NAME }}
          path: .
      - name: Submit to Google Chrome Web Store
        run: npx chrome-webstore-upload-cli@2 upload --source ${{ env.ZIP_NAME }} --extension-id ${{ secrets.EXTENSION_ID }} --client-id ${{ secrets.CLIENT_ID }} --client-secret ${{ secrets.CLIENT_SECRET }} --refresh-token ${{ secrets.REFRESH_TOKEN }} --auto-publish